
server {
  listen 80;
  server_name magento.local;
  root /var/www/html/pub;
  index index.php;


  fastcgi_buffers 16 16k;
  fastcgi_buffer_size 32k;

  client_max_body_size 64M;

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  
# -----------------------------
# Magento static files
# -----------------------------
location /static/ {
    # In production mode you can enable this for caching
    # expires max;

    # Remove signature (version12345) from static files URL
    location ~ ^/static/version {
        rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
    }

    # Try to serve file directly, otherwise route to static.php with resource param
    if (!-f $request_filename) {
        rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
    }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header Access-Control-Allow-Origin "*" always;
}

# -----------------------------
# Magento media files
# -----------------------------
location /media/ {
    try_files $uri $uri/ /get.php$is_args$args;

    location ~ ^/media/theme_customization/.*\.xml {
        deny all;
    }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header Access-Control-Allow-Origin "*" always;
}


  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
    fastcgi_read_timeout 1800;
  }
}
